name: Docker Testing

on: push

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t mermeid .
      - name: Run Docker image
        run: docker run --rm -p 8080:8080 -d mermeid
      - name: Check the deployed service URL
        run: i=0 ; while (! curl --fail -sv http://localhost:8080/index.html) ; do if ((i > 20)) ; then echo ' **** timeout ... aborting **** ' ; exit 1 ; else sleep 5 ; echo waiting for container ... ; i=$((i+1)) ; fi ; done

